### ISSUE TITLE
A landing page that explain the main goals of Contribution

### ISSUE THREAD

**Issue by magmukendi** [roopeshsn/conception#16]
**Is your feature request related to a problem? Please describe.**

As of now, when people visit Contribution's URL, they land directly on the main page which does not clearly explain what Contribution does. They are bombed with the call to action to contribute to the project.

**Describe the solution you'd like**
How about adding the following before doing any call to action?:
- a short description of Contribution on the top of the page,
- Count the number of contributions already made
- From where they have been made

For reference, you can check the screenshot below from [Ideo](https://www.ideo.com/about)
![Example of Ideo](https://user-images.githubusercontent.com/64711820/196038962-86e8d87f-5dab-417e-89de-adb016f12b91.png)

I will be glad to work on this issue.

**Comment by roopeshsn** [comment]
Hi, @LeGrandMAG You can work on this issue!

**Comment by roopeshsn** [comment]
The data on the page should not be static. It should be dynamic. Every time it should update automatically. Also, count the number of ideas submitted.
