### ISSUE TITLE
Update the favicon

### ISSUE THREAD

**Issue by magmukendi** [roopeshsn/conception#17]
**Is your feature request related to a problem? Please describe.**
If I am not wrong, the current fav icon is just vercel's logo. 

**Describe the solution you'd like**
How about adding a Favicon that represents the vision of the project, A light bulb for instance? 

I designed a simple logo symbolizing idea ,ideation that you can use as favicon. (See screenshot below)

![Favicon logo](https://user-images.githubusercontent.com/64711820/196040912-fbab7851-2329-4a91-887c-9cdb7dbd9aae.png)

I would like to work on applying this.

**Comment by roopeshsn** [comment]
Go a head @LeGrandMAG
