### ISSUE TITLE
User-friendly page title

### ISSUE THREAD

**Issue by magmukendi** [roopeshsn/conception#18]
**Is your feature request related to a problem? Please describe.**
As of now when I switch to a different page, it just displays the URL as the page title, which is not user-friendly at all.

![image](https://user-images.githubusercontent.com/64711820/196041235-69efeefb-a437-4c31-8ce8-154b5cb2f9e5.png)

**Describe the solution you'd like**
I would like to make it more user-friendly by changing the page title so that it displays "College Project Ideas" or "App ideas"

I would be glad to work on this.

**Comment by roopeshsn** [comment]
Yeah, create that below the tags mentioned.
